### ISSUE TITLE
Open Source - For Linux/OSX users to create their own version?

### ISSUE THREAD

**Issue by OdinsHat** [SanderSade/sbClient#3]
I'm hoping you'd consider open-sourcing the DLL's/dev info to enable a Linux version to be created?

Any information, source code, sources, anything at all that could help Linux/OSX users such as myself to engineer a version for ourselves would be very much appreciated.

I look forward to your response.

**Comment by Sophist-UK** [comment]
SBclient is primarily a mIRC script, and mIRC is (AFAIK) windows only. I doubt that mIRC could be ported to Linux, but it is possible that AdiIRC (which is largely but not entirely compatible with mIRC) and is written in dotNet could be ported to Linux though AFAIK this has not happened yet. So I am struggling to see why you are asking this question, to be honest.

However, assuming that this is still a meaningful question...

According to the Duke's (ancient) web site, the dll is the same DLL used in SearchBot (the server that SBclient talks to). 

SBclient is primarily a script that automates the processing and display of the SearchBot search results file. Whilst (obviously) the search DLL is an essential element of SearchBot, it is NOT used in the primary functionality of sbClient, and is provided (AFAIK) only for separate minor functionality in SBclient which provides local search functionality.

Assuming you have a mIRC script compatible Linux IRC client, my advice to you would be to strip out the local search functionality from SBclient and implement the primary functionality without local search.

If you want local search functionality in your IRC client on Linux, then I imagine that there are a variety of local search solutions available for Linux / Mac which you could hook into from whatever Linux IRC client you are using.

**Comment by Sophist-UK** [comment]
P.S. As per #1 the DLL here is NOT the same as the one used by Ook's more recent versions of sbClient.

**Comment by SanderSade** [comment]
The DLL was written by Iczelion (of the [Iczelion's Win32 Assembly](http://www.interq.or.jp/chubu/r6/masm32/tute/tute001.html) fame) close to 20 years ago. I am not sure I even have the source - might exist on some old CD, or it might not...

Like Sophist said, the DLL is only used for local searches, everything else is handled by the mIRC script. With the speed of the current computers vs 20 years ago, the local search is probably doable with just script, no dll required.

Also, what do you mean "(ancient) web site", I updated it less than a decade ago... :P

**Comment by Sophist-UK** [comment]
Well, @SanderSade , "ancient" is of course a relative term. By comparison to the age of the universe, you last update was very very very very recent indeed.

**Comment by OdinsHat** [comment]
Thank you all @Sophist-UK & @SanderSade. I understand the purpose better now and think it should be possible to write something similar for Weechat and/or HexChat on Linux.
